# Dataset configuration context

# name of the dataset
name = "AIFB"

[graph]
context = "../../datasets/aifb/aifb_revised_stripped.nt.gz"
train = "../../datasets/aifb/aifb_train_set.nt.gz"
valid = "../../datasets/aifb/aifb_valid_set.nt.gz"
test = "../../datasets/aifb/aifb_test_set.nt.gz"

[graph.structural]
include_inverse_properties = true
exclude_properties = []  # use empty list to include all
separate_literals = false
multiprocessing = false

[[graph.features]]
datatype = 'xsd.numeric'
include = false
share_weights = false
embedding_dim = 4
p_dropout = 0.0
p_noise = 0.0
noise_multiplier = 0.0

[[graph.features]]
datatype = 'xsd.gYear'
include = false
share_weights = true
embedding_dim = 1
p_dropout = 0.0
p_noise = 0.0
noise_multiplier = 0.0

#[[graph.features]]
#datatype = 'xsd.date'
#include = false
#share_weights = true 
#p_dropout = 0.0
#
#[[graph.features]]
#datatype = 'xsd.boolean'
#include = false
#share_weights = true 
#p_dropout = 0.0

[[graph.features]]
datatype = 'xsd.string'
include = false
share_weights = true
trim_outliers = false
remove_outliers = true
embedding_dim = 32
p_dropout = 0.0
p_noise = 0.0
noise_multiplier = 0.0

#[[graph.features]]
#datatype = 'blob.image'
#include = false
#share_weights = true
#trim_outliers = false
#remove_outliers = false
#embedding_dim = 128
#p_dropout = 0.0
#
#[[graph.features]]
#datatype = 'ogc.wktLiteral'
#include = false
#share_weights = true
#remove_outliers = false
#embedding_dim = 16
#p_dropout = 0.0

[task]
type = "node classification"
target_property = 'http://swrc.ontoware.org/ontology#affiliation'
target_property_inv = 'http://swrc.ontoware.org/ontology#employs'
seed = -1  # use < 0 for random
model_on_gpu = false
batchsize = -1  # < 1 for full batch

[model]
epoch = 50
learning_rate = 0.01
num_bases = 0
p_dropout = 0
weight_decay = 0.0
l1_lambda = 0.0
l2_lambda = 0.0
bias = false

[[model.layers]]
type = 'mrgcn'
hidden_nodes = 16

[[model.layers]]
type = 'mrgcn'
