# Dataset configuration context

# name of the dataset
name = "AM"

[graph]
context = "../../datasets/am/am_stripped_revised_updated.nt.gz"
train = "../../datasets/am/am_train_set.nt.gz"
valid = "../../datasets/am/am_valid_set.nt.gz"
test = "../../datasets/am/am_test_set.nt.gz"

[graph.structural]
include_inverse_properties = true
exclude_properties = []  # use empty list to include all
separate_literals = false
multiprocessing = false

[[graph.features]]
datatype = 'xsd.numeric'
include = true
share_weights = false

[[graph.features]]
datatype = 'xsd.gYear'
include = true
share_weights = false
embedding_dim = 1

[[graph.features]]
datatype = 'xsd.date'
include = true
share_weights = false
embedding_dim = 3

[[graph.features]]
datatype = 'xsd.boolean'
include = true
share_weights = false

[[graph.features]]
datatype = 'xsd.string'
include = true
num_batches = 16
share_weights = true
trim_outliers = false
remove_outliers = false
embedding_dim = 16

[[graph.features]]
datatype = 'blob.image'
include = true
num_batches = 16
share_weights = false
remove_outliers = false
embedding_dim = 128

#[[graph.features]]
#datatype = 'ogc.wktLiteral'
#include = true
#num_batches = 16
#share_weights = false
#trim_outliers = false
#remove_outliers = false
#embedding_dim = 16

[task]
type = 'node classification'
target_property = 'http://purl.org/collections/nl/am/objectCategory'
target_property_inv = 'http://purl.org/collections/nl/am/material'
seed = -1  # use < 0 for random
model_on_gpu = false

[model]
epoch = 50
learning_rate = 0.01
patience = 7  # < 0 to disable
num_bases = 40
p_dropout = 0.0
l2norm = 5e-4
bias = false

[[model.layers]]
type = 'mrgcn'
hidden_nodes = 10

[[model.layers]]
type = 'mrgcn'
