# Dataset configuration file

# name of the dataset
name = "AM"

[graph]
file = "../../datasets/am/am_stripped_revised_updated.nt.gz"
train = "../../datasets/am/am_train_set.nt.gz"
valid = "../../datasets/am/am_valid_set.nt.gz"
test = "../../datasets/am/am_test_set.nt.gz"

[graph.structural]
include_inverse_properties = true
exclude_properties = []  # use empty list to include all
separate_literals = false

[[graph.features]]
datatype = 'xsd.numeric'
include = false
share_weights = false

[[graph.features]]
datatype = 'xsd.gYear'
include = false
share_weights = false

[[graph.features]]
datatype = 'xsd.date'
include = false
share_weights = false

[[graph.features]]
datatype = 'xsd.boolean'
include = false
share_weights = false

[[graph.features]]
datatype = 'xsd.string'
include = true
passes_per_batch = 1
share_weights = true
remove_outliers = false

[[graph.features]]
datatype = 'blob.image'
include = false
passes_per_batch = 1
share_weights = false
remove_outliers = false

[[graph.features]]
datatype = 'ogc.wktLiteral'
include = false
passes_per_batch = 1
share_weights = false
remove_outliers = false

[task]
# node classification
target_property = 'http://purl.org/collections/nl/am/objectCategory'
target_property_inv = 'http://purl.org/collections/nl/am/material'
seed = -1  # use < 0 for random
gpu = false

[model]
epoch = 50
learning_rate = 0.01
patience = 7  # < 0 to disable
mini_batch = false
num_bases = 40
p_dropout = 0.0
l2norm = 5e-4
bias = false

[[model.layers]]
type = 'mrgcn'
hidden_nodes = 10

[[model.layers]]
type = 'mrgcn'
