# Dataset configuration file
version = 0.1

# name of the dataset
name = "BGS"

[graph]
file = "../../datasets/bgs/bgs_revised.nt.gz"

[graph.structural]
include_inverse_properties = true
exclude_properties = []  # use empty list to include all
separate_literals = false

[[graph.features]]
datatype = 'xsd.numeric'
include = true
share_weights = true

[[graph.features]]
datatype = 'xsd.gYear'
include = true
share_weights = true

[[graph.features]]
datatype = 'xsd.date'
include = true
share_weights = true

[[graph.features]]
datatype = 'xsd.boolean'
include = true
share_weights = true

[[graph.features]]
datatype = 'xsd.string'
include = true
passes_per_batch = 1
share_weights = true
remove_outliers = false

[[graph.features]]
datatype = 'blob.image'
include = true
passes_per_batch = 1
share_weights = true
remove_outliers = false

[[graph.features]]
datatype = 'ogc.wktLiteral'
include = true
passes_per_batch = 1
share_weights = true
remove_outliers = false

[task]
# node classification
instance_type = ''
target_property = 'http://data.bgs.ac.uk/ref/Lexicon/hasLithogenesis'
target_property_inv = ''
target_classes = []
dataset_ratio = [0.7, 0.2, 0.1]  # train, test, validation
kfolds = 10  # use < 0 to disable (single run)
seed = -1  # use < 0 for random
gpu = false

[model]
epoch = 50
learning_rate = 0.01
patience = 7  # < 0 to disable
mini_batch = false
num_bases = 40
p_dropout = 0.0
l2norm = 5e-4
bias = false

[[model.layers]]
type = 'mrgcn'
hidden_nodes = 16

[[model.layers]]
type = 'mrgcn'

