# Dataset configuration file

# name of the dataset
name = "DMG4C"

[graph]
file = "../../datasets/dmg/dataset.subset/baseline/monumentsT4C_full-dummyimg.nt.gz"

[graph.structural]
include_inverse_properties = true
exclude_properties = []  # use empty list to include all
separate_literals = false

[[graph.features]]
datatype = 'xsd.numeric'
include = true
share_weights = false

[[graph.features]]
datatype = 'xsd.date'
include = true
share_weights = false 

[[graph.features]]
datatype = 'xsd.boolean'
include = true
share_weights = false

[[graph.features]]
datatype = 'xsd.gYear'
include = true
share_weights = false

[[graph.features]]
datatype = 'xsd.string'
include = true
passes_per_batch = 1
share_weights = false
remove_outliers = false

[[graph.features]]
datatype = 'blob.image'
include = true
passes_per_batch = 1
share_weights = false
remove_outliers = false

[[graph.features]]
datatype = 'ogc.wktLiteral'
include = true
passes_per_batch = 1
share_weights = false
remove_outliers = false

[task]
# node classification
target_property = 'https://data.labs.pdok.nl/rce/def/monumentCode'
target_property_inv = ''
seed = -1  # use < 0 for random
gpu = false

[model]
epoch = 50
learning_rate = 0.01
patience = 7  # < 0 to disable
mini_batch = false
num_bases = 40
p_dropout = 0.0
l2norm = 5e-4
bias = false

[[model.layers]]
type = 'mrgcn'
hidden_nodes = 16

[[model.layers]]
type = 'mrgcn'
