# Dataset configuration context

# name of the dataset
name = "DMG4C"

[graph]
context = "../../datasets/dmg/dataset.subset/dmg.nt.gz"
train = "../../datasets/dmg/dataset.subset/dmg_train_set.nt.gz"
valid = "../../datasets/dmg/dataset.subset/dmg_valid_set.nt.gz"
test = "../../datasets/dmg/dataset.subset/dmg_test_set.nt.gz"

[graph.structural]
include_inverse_properties = true
exclude_properties = []  # use empty list to include all
separate_literals = false
multiprocessing = false

[[graph.features]]
datatype = 'xsd.numeric'
include = true
share_weights = false

[[graph.features]]
datatype = 'xsd.date'
include = true
share_weights = false 

[[graph.features]]
datatype = 'xsd.boolean'
include = true
share_weights = false

[[graph.features]]
datatype = 'xsd.gYear'
include = true
share_weights = false

[[graph.features]]
datatype = 'xsd.string'
include = true
num_batches = 16
share_weights = false
trim_outliers = false
remove_outliers = false
embedding_dim = 16

[[graph.features]]
datatype = 'blob.image'
include = true
num_batches = 16
share_weights = false
remove_outliers = false
embedding_dim = 128

[[graph.features]]
datatype = 'ogc.wktLiteral'
include = true
num_batches = 16
share_weights = false
trim_outliers = false
remove_outliers = false
embedding_dim = 16

[task]
type = 'node classification'
target_property = 'https://data.labs.pdok.nl/rce/def/monumentCode'
target_property_inv = ''
seed = -1  # use < 0 for random
gpu = false

[model]
epoch = 50
learning_rate = 0.01
patience = 7  # < 0 to disable
num_bases = 40
p_dropout = 0.0
l2norm = 5e-4
bias = false

[[model.layers]]
type = 'mrgcn'
hidden_nodes = 16

[[model.layers]]
type = 'mrgcn'
