# Dataset configuration file
version = 0.1

# name of the dataset
name = "DMG4C"

[graph]
file = "../../datasets/dmg/dataset.subset/baseline/monumentsT4C_full-dummyimg.nt.gz"

[graph.structural]
include_inverse_properties = true
exclude_properties = []  # use empty list to include all
normalize = true

[[graph.features]]
datatype = 'xsd.gYear'
include = false
normalize = true

[[graph.features]]
datatype = 'xsd.string'
include = true
[[graph.features.layers]]
type = 'Conv1d'
nchannels_in = 1
nchannels_out = 18
kernel_size = 3
stride = 1
padding = 1
activation = 'ReLU'
[[graph.features.layers]]
type = 'MaxPool2d'
kernel_size = 2
stride = 2
[[graph.features.layers]]
type = 'Linear'
indim = 18 * ?
hidden_nodes = ?
activation = 'ReLU'
[[graph.features.layers]]
outdim = ?

[task]
# node classification
instance_type = 'http://dbpedia.org/ontology/Monument'
target_property = 'https://data.labs.pdok.nl/rce/def/monumentCode'
target_property_inv = ''
target_classes = ["https://data.labs.pdok.nl/rce/def/woonhuis", 
                  "https://data.labs.pdok.nl/rce/def/agrarischGebouw",
				  "https://data.labs.pdok.nl/rce/def/losObject",
				  "https://data.labs.pdok.nl/rce/def/kerk"]
dataset_ratio = [0.7, 0.2, 0.1]  # train, test, validation
kfolds = -1  # use < 0 to disable (single run)
seed = -1  # use < 0 for random
gpu = false

[model]
epoch = 50
learning_rate = 0.01
loss = 'categorical_crossentropy'
num_bases = 40
p_dropout = 0.0
l2norm = 5e-4
bias = false

[[model.layers]]
type = 'mrgcn'
hidden_nodes = 16

[[model.layers]]
type = 'mrgcn'
