# Dataset configuration context

# name of the dataset
name = "FB15K"

[graph]
train = "../../datasets/fb15k/rdf/freebase_mtr100_mte100-train.nt.gz"
valid = "../../datasets/fb15k/rdf/freebase_mtr100_mte100-valid.nt.gz"
test = "../../datasets/fb15k/rdf/freebase_mtr100_mte100-test.nt.gz"

[graph.structural]
include_inverse_properties = true
exclude_properties = []  # use empty list to include all
separate_literals = false

[[graph.features]]
datatype = 'xsd.numeric'
include = false
share_weights = false

[[graph.features]]
datatype = 'xsd.boolean'
include = false
share_weights = false

[[graph.features]]
datatype = 'xsd.gYear'
include = false
share_weights = false

[[graph.features]]
datatype = 'xsd.date'
include = false
share_weights = false

[[graph.features]]
datatype = 'xsd.string'
include = false
passes_per_batch = 1
share_weights = false
remove_outliers = false

[[graph.features]]
datatype = 'blob.image'
include = false
passes_per_batch = 1
share_weights = false
remove_outliers = false

[[graph.features]]
datatype = 'ogc.wktLiteral'
include = false
passes_per_batch = 1
share_weights = false
remove_outliers = false

[task]
type = 'link prediction'
seed = -1  # use < 0 for random
gpu = false

[model]
epoch = 50
learning_rate = 0.01
patience = 7  # < 0 to disable
mini_batch = false
num_bases = 0
p_dropout = 0.0
l2norm = 0.0
bias = false

[[model.layers]]
type = 'mrgcn'
hidden_nodes = 16

[[model.layers]]
type = 'mrgcn'
