# Dataset configuration context

# name of the dataset
name = "FB15K-237"

[graph]
# available at https://gitlab.com/wxwilcke/mmkg
train = "../../datasets/fb15k-237/rdf/freebase_mtr100_mte100_237-train.nt.gz"
valid = "../../datasets/fb15k-237/rdf/freebase_mtr100_mte100_237-valid.nt.gz"
test = "../../datasets/fb15k-237/rdf/freebase_mtr100_mte100_237-test.nt.gz"

[graph.structural]
include_inverse_properties = true
exclude_properties = []  # use empty list to include all
separate_literals = false
multiprocessing = false

#[[graph.features]]
#datatype = 'xsd.numeric'
#include = true
#share_weights = true
#p_dropout = 0.0
#
#[[graph.features]]
#datatype = 'xsd.boolean'
#include = true
#share_weights = true
#p_dropout = 0.0
#
#[[graph.features]]
#datatype = 'xsd.gYear'
#include = true
#share_weights = true
#p_dropout = 0.0
#
#[[graph.features]]
#datatype = 'xsd.date'
#include = true
#share_weights = true
#p_dropout = 0.0
#
#[[graph.features]]
#datatype = 'xsd.string'
#include = true
#num_batches = 16
#share_weights = true
#trim_outliers = false
#remove_outliers = false
#embedding_dim = 16
#p_dropout = 0.0
#
#[[graph.features]]
#datatype = 'blob.image'
#include = true
#num_batches = 16
#share_weights = true
#remove_outliers = false
#embedding_dim = 128
#p_dropout = 0.0
#
#[[graph.features]]
#datatype = 'ogc.wktLiteral'
#include = true
#num_batches = 16
#share_weights = true
#trim_outliers = false
#remove_outliers = false
#embedding_dim = 16
#p_dropout = 0.0

[task]
type = 'link prediction'
filter_ranks = false
seed = -1  # use < 0 for random
model_on_gpu = false
distmult_on_gpu = false
eval_interval = 10
filter_ranks = true
mrr_batch_size = 5e1
batchsize = -1  # < 0 for full batch
early_stopping.patience = -1
early_stopping.tolerance = 0.01

[model]
epoch = 20
learning_rate = 0.01
num_bases = 2
p_dropout = 0.0
weight_decay = 0.0
l1_lambda = 0.0
l2_lambda = 0.0
bias = false

[[model.layers]]
type = 'mrgcn'
hidden_nodes = 200
