# Dataset configuration context

# name of the dataset
name = "FB15K"

[graph]
train = "../../datasets/fb15k/rdf/freebase_mtr100_mte100-train.nt.gz"
valid = "../../datasets/fb15k/rdf/freebase_mtr100_mte100-valid.nt.gz"
test = "../../datasets/fb15k/rdf/freebase_mtr100_mte100-test.nt.gz"

[graph.structural]
include_inverse_properties = true
exclude_properties = []  # use empty list to include all
separate_literals = false

[[graph.features]]
datatype = 'xsd.numeric'
include = true
share_weights = true

[[graph.features]]
datatype = 'xsd.boolean'
include = true
share_weights = true

[[graph.features]]
datatype = 'xsd.gYear'
include = true
share_weights = true

[[graph.features]]
datatype = 'xsd.date'
include = true
share_weights = true

[[graph.features]]
datatype = 'xsd.string'
include = true
passes_per_batch = 1
share_weights = true
trim_outliers = false
remove_outliers = false

[[graph.features]]
datatype = 'blob.image'
include = true
passes_per_batch = 1
share_weights = true
remove_outliers = false

[[graph.features]]
datatype = 'ogc.wktLiteral'
include = true
passes_per_batch = 1
share_weights = true
trim_outliers = false
remove_outliers = false

[task]
type = 'link prediction'
seed = -1  # use < 0 for random
gpu = false

[model]
epoch = 200
learning_rate = 0.01
patience = -1  # < 0 to disable
mini_batch = false
distmult_batch_size = 1e5
mrr_batch_size = 5e3
num_bases = 2
p_dropout = 0.0
l2norm = 0.01
bias = false

[[model.layers]]
type = 'mrgcn'
hidden_nodes = 200
