### ONLY FOR TESTING ###

# name of the dataset
name = "SYNTH"

[graph]
# available at https://gitlab.com/wxwilcke/mmkg
context = "../../datasets/synth/context.nt.gz"

train = "../../datasets/synth/train.nt.gz"
valid = "../../datasets/synth/valid.nt.gz"
test = "../../datasets/synth/test.nt.gz"

[graph.structural]
include_inverse_properties = true
exclude_properties = []  # use empty list to include all
separate_literals = false
multiprocessing = false

[[graph.features]]
datatype = 'xsd.numeric'
include = true
share_weights = true
embedding_dim = 4
p_dropout = 0.0
p_noise = 0.0
noise_multiplier = 0.0

[[graph.features]]
datatype = 'xsd.gYear'
include = true
share_weights = true 
embedding_dim = 1
p_dropout = 0.0
p_noise = 0.0
noise_multiplier = 0.0

[[graph.features]]
datatype = 'xsd.string'
include = true
share_weights = true
trim_outliers = true
remove_outliers = false
embedding_dim = 16
p_dropout = 0.0
model = [ "huggingface/pytorch-transformers",
          "model",
          "distilbert-base-multilingual-cased" ]
tokenizer.config = [ "huggingface/pytorch-transformers",
                     "tokenizer",
                     "distilbert-base-multilingual-cased" ]
tokenizer.pad_token = "[PAD]"


[[graph.features]]
datatype = 'blob.image'
include = true
share_weights = true
embedding_dim = 128
p_dropout = 0.0
p_noise = 0.0
noise_multiplier = 0.0
model = [ "pytorch/vision:v0.10.0",
          "mobilenet_v2",
          "MobileNet_V2_Weights.IMAGENET1K_V1" ]
transform.mode = "RGB"
transform.interpolationMode = "BILINEAR"
transform.resizeSize = 232
transform.centerCrop = 224
transform.mean = [0.485, 0.456, 0.406]
transform.std = [0.229, 0.224, 0.225]


[[graph.features]]
datatype = 'ogc.wktLiteral'
include = true
share_weights = true
trim_outliers = true
remove_outliers = false
embedding_dim = 16
p_dropout = 0.0
p_noise = 0.0
noise_multiplier = 0.0

[task]
# node classification
type = 'node classification'
instance_type = ''
target_property = ''
target_property_inv = ''
target_classes = []
seed = -1  # use < 0 for random
model_on_gpu = false
batchsize = -1  # < 0 for full batch

[model]
epoch = 100
learning_rate = 0.01
num_bases = 0
p_dropout = 0.0
weight_decay = 0.0
l1_lambda = 0.0
l2_lambda = 0.0
bias = false

[[model.layers]]
type = 'mrgcn'
hidden_nodes = 16

[[model.layers]]
type = 'mrgcn'
